### ISSUE TITLE
suggestion: `example` keywords

### ISSUE THREAD

**Issue by geemus** [json-schema/json-schema#104]
It can be very useful/informative to include an `example` value along with given attributes. I've been using it and have found it pretty helpful (especially when generating documentation from the schema).

**Comment by tobie** [comment]
Also think this is worthwhile, but how would it work in practice?

It somehow needs to be as composable as the rest of JSON Schema, if not your examples are going to become stale really quickly. In practice it seems you only really need an `example` property for strings and for `patternProperties`, no? Examples for numbers and booleans are trivial to generate. Arrays and object aren't difficult either.

So all you would really need would be an `example` keyword for strings (which could also go on numbers, why not, after all), and something like a `patternPropertyExamples` on objects which would be an array of strings, e.g:

``` json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "patternProperties": {
        "^(/[^/]+)+$": {}
    },
    "patternPropertyExamples": ["/var/www", "/var", "/tmp"]
}
```
Am I missing anything?

**Comment by geemus** [comment]
Hmm, interesting. I hadn't really thought about being able to generate some values more automatically, I can understand the concern around stale values, but so far we haven't really experienced it as a problem in practice (yet anyway).

It would definitely trim down how much the schema differed from one another and/or how much you had to write though. I suppose strings which have a pattern wouldn't necessarily need an explicit example either as you should have enough info to reverse engineer it. I suspect that allowing (albeit not requiring) example anywhere might be helpful though, ie maybe `1` is a reasonable default for numbers, but if the values for a particular thing are consistently orders-of-magnitude away from `1`, a number that is more akin to the data might be more informative.

In general though, definitely agree that it is useful, but could be used less and more simply while keeping the same effect. I'll definitely think on it more and note it on the documentation generator I use as a possible thing to pursue (https://github.com/interagent/prmd/issues/199).

Thanks!

**Comment by tobie** [comment]
>  I suppose strings which have a pattern wouldn't necessarily need an explicit example either as you should have enough info to reverse engineer it.

That seems non-trivial and won't necessarily produce good examples. Consider the case where you'd want to verify a string only contains a first name, you'd use something like this `"^[A-Z][a-z]+(-[A-Z][a-z]+)?$"`. There is not enough info embedded in this pattern to find out that the expected content is a first name (and not a random string of characters). So generated examples might more often than not resemble: `"erfuohoeom-ejij"` instead of `"Marie-Pierre"` or `"Fred"`.

That would however work well with `enums`.

> I suspect that allowing (albeit not requiring) example anywhere might be helpful though, ie maybe 1 is a reasonable default for numbers, but if the values for a particular thing are consistently orders-of-magnitude away from 1, a number that is more akin to the data might be more informative.

Yes that is true of numbers (though max an min values can be leveraged in that case). But it isn't of booleans or `null`.

**Comment by gilesbowkett** [comment]
One alternative could be a sort of "literate schema," like [literate CoffeeScript](http://coffeescript.org/#literate). I see a lot of APIs which provide documentation but not schemas, and the best answer is probably both.

**Comment by geemus** [comment]
@toble Hmm, yeah. Figuring it out from the regex wouldn't have good results in many cases. I guess I just worry that it might not have great results in many cases (ie the orders-of-magnitude off number case). Some things can mitigate, but a human provided realistic example may often win out (though not always).

@gilesbowkett interesting. I hadn't really been familiar with that. We've had fairly good success with schemas that we generate markdown off of, but there have definitely been some cases of things where it wasn't a good fit or we'd like to change just one section that have been challenging or not really possible. Something along these lines could be an interesting way to try and navigate it.

**Comment by tobie** [comment]
@geemus agree. Example strings should go on numbers and strings, plus an `examplePatternProperties`. As indicated above, patterns aren't enough to reverse-engineer credible examples. However, `enum`, `default`, `format`, `min` and `max`, etc. can be leveraged by implementations when `example` is missing (this need not be normatively specified anywhere, it's a quality of implementation issue of the documentation tool).

@gilesbowkett so while I like the concept (and how that works for CS) I'm not sure I understand how it would apply to JSON schemas (especially due to JSON not supporting comments). Is what you had in mind something like [RAML](http://raml.org/), but looser?

**Comment by gilesbowkett** [comment]
@geemus @tobie It's a real pity JSON can't do comments. re RAML, the awesome thing about standards is that there's so many of them. I hadn't seen that, I'll have to dive in. Another mechanism might be if you had an example document as well as a schema, and you could throw them into some kind of Markdown-generating blender.

Keeping with the actual idea of this Issue, though, I think in many cases (not just w/`enum`s and regexes) you'd need to have multiple `example` strings. [Names](http://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/) and [times](http://infiniteundo.com/post/25326999628/falsehoods-programmers-believe-about-time) are obvious examples (or I suppose meta-examples, since they're examples of examples).

I'm not 100% sure whether this should be in the schema, as an `example` string, or in a separate doc/tool, as in the (half-baked, off-the-top-of-my-head) idea of a schema/example blender. But with staleness, my gut reaction is to say that goes in a tool. Basically, the spec says that any `example` string must indeed be a valid example, and then your validator can automatically determine that.

(e.g., any schema which gives `4` as an example of a string just fails validation.)

The value of putting it in a tool is that it's probably going to express some kind of business or application logic, and building that into your schema makes less sense than building it into your app. So your tool reads the schema, but can also pull in your app/biz logic, if need be.

**Comment by tobie** [comment]
@gilesbowkett aren't standards fun!?

So you make a valid point about wanting to have multiple examples. I was going to suggest the  `example` prop could take a string/int or an array of strings/ints (similar to how `type` is handled).

As you suggest, the other option is external examples. This might notably be more appropriate when you have constraints that cannot be expressed in terms of JSON Schema (e.g. props that are only relevant is another boolean prop is `true` somewhere, etc.

As you mention, most of this is essentially a tools issues, with the next version of the spec eventually paving the cowpath if need be. So let's start cranking.

**Comment by geemus** [comment]
Great discussion! I think I'll definitely see about doing something around defaults in prmd in the mean time so we can prove out the idea further.

I guess on a related note, `comment` or something like that might be another thing that could be interesting (since json doesn't do it otherwise). ie `a field for providing information or instruction to the end user`. Obviously a really rough idea, which even I am not totally sold on, but a possibility anyway.

**Comment by geemus** [comment]
A bit of an aside, but we actually use yaml to write our schemas most of the time (and then just turn it in to json before publishing, as it is a simple translation). We have just found that for many people it can be easier to deal with in cases where you need to hand edit schemas. Another benefit of that, which I hadn't previously considered, is that it would allow comments. Anyway, perhaps something interesting there so I thought I would share.

**Comment by howardroark** [comment]
@geemus 100% agree.  It is just a very human way to communicate context, as we can infer so much from a good example.  I wouldn't look at it in terms of what a machine will do with the value, but more so someone looking to learn about the application through the schema.  As you said It would be really handy for generating a good human centric documentation example.  

Designers, developers and strategists alike can benefit from that.  I plan to incorporate "example" into my schema design and then use it to output a designer friendly visualization of the schema in a sort of reference doc.  That way the entire team can reference those docs and always be on the same page about the data available to work with in the app.  If a strategist can look at the schema and decide if their direction can be accomplished without changing data, you can really help out the process.  Plus, it puts the schema front and centre and exposes it to more conversation, be it pragmatic or philosophical. 

I'd love to see it as an official part of the schema :)

**Comment by handrews** [comment]
@geemus work is now going on at https://github.com/json-schema-org/json-schema-spec
If you'd like to continue to advocate for this, please re-open it at the new schema.
It would be most appreciated if you could close this issue; we no longer have permissions on this repo.
