### ISSUE TITLE
Proposal: `propertyOrder`

### ISSUE THREAD

**Issue by fge** [json-schema/json-schema#119]
The JSON specification clearly states that the order of members in a JSON Object is of no importance; however, in many cases, such an order is important.

The proposal here is to help user interfaces define an order in which inputs for properties should be displayed; for instance:

``` json
{
    "propertyOrder": [ "name", "surname", "address" ]
}
```

Comments?

**Comment by Fannon** [comment]
Wouldn't that problem not occur in the first place, if properties were an array? JavaScript Objects are unordered by default.

See this Gist: https://gist.github.com/Fannon/1052577fe58b347798b7

**Comment by bugventure** [comment]
+1 for @Fannon 
I can easily imagine `properties` accepting an array of schemas to indicate property order is important and must be validated.

This approach still doesn't solve the problem for multi-schema keywords `anyOf`, `allOf` and `oneOf`, as well as `patternProperties`, but is more concise than having to list all property names in an array.

Having a `propertyOrder` array does not solve the problem with `patternProperties` either, unless we have a regular expression string as a valid item in the properties array. But then, you'd need a notation to discern the regex string from a regular string specifying an exact property name.

**Comment by epoberezkin** [comment]
what is the purpose of this validation? Is there any json implementation that allows to specify the order of object properties when objects are serialised?

**Comment by Fannon** [comment]
To, this problem doesn't arise with validation. It is just an issue if JSON Schema is used to generate the Forms / UI, too.

**Comment by epoberezkin** [comment]
If the order is important you should always use arrays. Order of object properties in both JSON and in JavaScript is not defined, can be different in each iteration. It is implementation dependent.

**Comment by Fannon** [comment]
Well, from the validation point of view using an object is the most reasonable decision. 
It's really not important in which order the informations are stored / validated.

But if you want to generate that form, you'd like to have a fixed order of the input fields. (From an UI/UX point of view)

Of course you're right. If the order is of importance, an array should be chosen instead of an object. The problem I've mentioned is however a problem of different requirements of different use-cases of the same schema.

**Comment by mitar** [comment]
I would also appreciate such a feature. I the main question here is how to address the union types like `anyOf`. I think the solution could be a special keyword in the array. Something like:

```json
{
  "type": "object",
  "properties": {
    "prop1": { "type": "string" },
    "prop2": { "type": "string" }
  },
  "anyOf": [{
    "properties": {
      "prop3": { "type": "string" },
      "prop4": { "type": "string" }
    },
    "propertyOrder": ["prop4", "prop3"]
  }],
  "propertyOrder": ["prop1", {"$ref": "#/anyOf/0/propertyOrder"}, "prop2"]
}
```

This would could then display properties in a form in the order "prop1", "prop4", "prop3", "prop2".

**Comment by nemesisdesign** [comment]
I like `propertyOrder` or even simply `order` attribute in each property definition.

**Comment by epoberezkin** [comment]
I am not sure how can we define propertyOrder if by [JSON standard](http://www.json.org/) definition "An object is an __unordered__ set of name/value pairs". Any implementation relying on the object properties order is not complying with the JSON standard because even if some language supports the order of keys in the dictionary (and JavaScript does not) the JSON parser implementation is not obliged to maintain the same order.

I think we should not add something not consistent with JSON standard into JSON-schema standard.

The order can and should be implemented with arrays, JSON objects are unordered.

**Comment by epoberezkin** [comment]
If this propertyOrder is meant not as a validation keyword but as some additional information for some UI generators it should not be part of JSON-schema standard as well, it's just some additional information that can be included in the schema (it allows any additional properties).

**Comment by erosb** [comment]
I also don't find this proposal a good idea. It would be even impossible to properly support it in some of the implementations, since some of the JSON parser implementations also provide unordered maps after parsing.

**Comment by YurySk** [comment]
Agree with others, it seems to contradict the JSON specs as well as the fact than many JSON models use unordered maps.
If it wasn't for that the feature might be useful.

**Comment by sam-at-github** [comment]
:-1:  for being in core JSON Schema spec because its not applicable to validation of JSON data structures. 

There seem to be at least a couple of other proposals for keywords that are for UI concerns - [enumNames](https://github.com/json-schema/json-schema/wiki/enumNames-%28v5-proposal%29)/[choices](#211), [translations related ones](https://github.com/json-schema/json-schema/wiki/translations-%28v5-proposal%29). The existing spec itself seems to drift into this territory (some what) with `title`, `description`, `default`, `readOnly`, and the LDO stuff. These are kind of edge cases because they fall within the realm of validation as well. As already pointed out, currently UI's can just define there own keywords because JSON Schema ignores keywords it does not understand. Still, it would be some what valuable to standardize them. Maybe there should be an appendage to the spec for a small number of these UI-ish keywords in v5?

**Comment by epoberezkin** [comment]
@sam-at-github I like the idea of UI-specific set of keywords. I think they should be better thought through than currently. So maybe v6 :)? In any case, if the purpose is clear it's good. And it would also affect the naming. For example instead of `propertyOrder` (implies JSON territory) it can be `controlsOrder` / `inputOrder` etc. (or maybe even prefix whatever name with `ui`).

**Comment by epoberezkin** [comment]
Other useful UI specific things could be:

- `controlType` - input/text, input/password, select, radio, etc.
- `controlHidden` - with boolean or { $data } pointing to another value.
- `controlStyle`...

**Comment by erosb** [comment]
I still don't like the idea of adding UI-specific keywords to the schema
spec. IMO the json schema specification should have a single purpose:
validating json data; in other words, determining if a json document
matches the constraints expected by a schema. Any other usecase, like
supporting code generators, UI frameworks, etc should take place in a
separate specification. These usecases are valid, but not related to
validation. I'd prefer keeping the scope of this specification small: being
able to express data structure constraints. Making it something that is
able to express anything that is related to json and can be expressed
declaratively leads to creating an unmaintainable abomination, which is
both hard to learn and hard to implement.

2016-02-09 10:07 GMT+01:00 Evgeny Poberezkin <notifications@github.com>:

> Other useful UI specific things could be:
>
>    - controlType - input/text, input/password, select, radio, etc.
>    - controlHidden - with boolean or { $data } pointing to another value.
>    - controlStyle...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/json-schema/json-schema/issues/119#issuecomment-181770135>
> .
>



-- 


*Bence Erősme@github <https://github.com/erosb>*

**Comment by sam-at-github** [comment]
@erosb yeah agree with that sentiment. It would have to be made clear it was optional, and not relevant to validation. It would be essentially a separate spec. The core spec would be independent of it but it would be dependent on the core spec, much like the v4 hyper schema part. My preference would be to keep it minimal. I'm not really pushing for it though. @epoberezkin agreed they need to thought about more.

**Comment by YurySk** [comment]
Strongly agree with @erosb. Adding UI attributes to me is a clear case of scope creep.
The core V4 is an elegant specification of data composition with nothing but data composition primitives in it. No need to overload it with usage-specific stuff.

**Comment by epoberezkin** [comment]
Having view generation schema separate from data schema makes sense also because data structure is very often different from view structure.

The view schemas we use to generate UI have the structure following the view structure (groupings, tabs etc.) with a special field in each control pointing to the place in the data (we use JS property access syntax, json-pointer can be used too). That keeps view generation separate from data validation.

I guess the desire to have a reverse link (from JSON-schema to view-schema) is motivated by the need to highlight the controls failing validation. That can be achieved by simple tool-dependent control ID in JSON schema so that when validation fails it can be correlated to a particular control without the need to bring the whole view generation into JSON-schema standard.

But I am cool with both including and not including view generation as the standard subsection to be honest, as long as it is clearly separated. I guess the votes will be different depending on whether people are more UI / data (= frontend / backend ?) focused :)

**Comment by YurySk** [comment]
Just a couple if side comments. 
1. It sounds like the UI attribute ling of thinking almost inevitably lead to an idea of data binding. Which is a different beast altogether.
2. UI-centrism is just one way of looking at things. What about RESTful services, batch processing, analytics etc? Not every data use has UI in the picture.

**Comment by nemesisdesign** [comment]
I like the idea of having a new spec for UI centric extensions for JSON Schema.

**Comment by fuhrysteve** [comment]
I also agree with the idea of a new spec to accommodate these sorts of issues. I am using json-schema to generate UI schema in a couple places, and developed [this library](https://github.com/fuhrysteve/marshmallow-jsonschema) to further my efforts.

Unless there is a UI focused alternative, folks (not unlike myself) are just going to keep trying to shove UI components in. I find it extremely useful to be able to represent schemas in JSON for a UI to consume. So far, json-schema is the closest thing I've found that can be retro-fitted into accomplishing that end.

Here's a very short uncomprehensive list of all the other like-minded folks that are also trying to do this sort of thing:

https://github.com/jdorn/json-editor#property-ordering (obviously)
https://github.com/brutusin/json-forms
https://github.com/mozilla-services/react-jsonschema-form
https://github.com/jdorn/json-editor
https://github.com/ulion/jsonform

Is there an opportunity to start working on a UI focused spec?

**Comment by nemesisdesign** [comment]
It's not clear who's working on the draft 5 spec.

If we could have an open discussion about it with key people participating to the discussion I would be glad to participate in this effort.

I'm working on the [netjson](http://netjson.org) RFC, which refers to JSON-Schema. I'm working on software which implements the NetJSON spec and uses JSON-Schema for validation and UI generation purposes. I would be glad to help.

**Comment by nemesisdesign** [comment]
BTW people, remember that JSON-Schema already has some keywords that are not used for validation, think about *default*: it is used to supply default values when creating content.

**Comment by handrews** [comment]
@nemesisdesign , @fuhrysteve 
Active work is going on with the spec at https://github.com/json-schema-org/json-schema-spec where @awwright just published a new Internet Draft:
https://tools.ietf.org/html/draft-wright-json-schema-00
https://tools.ietf.org/html/draft-wright-json-schema-validation-00
https://tools.ietf.org/html/draft-wright-json-schema-hyperschema-00

This discussion would likely fall under json-schema-org/json-schema-spec#67
