### ISSUE TITLE
Need to display erro under each invalid fields on UI

### ISSUE THREAD

**Issue by Anshul-Batra** [json-schema/json-schema#204]
Hi,

I am planning to use JSON-schema for validating my HTML page. I have few fields on HTML page. Which when saved send a JSON data. When i validate JSON data with JSON schema, some fields it is showing invalid but is it possible to show an error message under those fields whose schema are not in compliance with data.

Thanks,
Anshul

**Comment by handrews** [comment]
@Anshul-Batra this is really an implementation question rather than a specification, although you may be interested in the JSON Schema UI proposal at json-schema-org/json-schema-spec#67

Could you please close this issue (there's no one left with the project who is able to close it otherwise) and join the discussion in the new repo if it is of interest?
