### ISSUE TITLE
switch (v5 proposal)

### ISSUE THREAD

**Issue by epoberezkin** [json-schema/json-schema#205]
https://github.com/json-schema/json-schema/wiki/switch-(v5-proposal)

As I understand that if `then` validation fails, the whole `switch` fails. if `continue: true` is present, should it still try the next one instead of failing?

And same in case if `then` succeeds.

Some better explanation of the idea would be great

**Comment by epoberezkin** [comment]
I implemented in ajv according to [this algorythm](https://github.com/epoberezkin/ajv/blob/master/KEYWORDS.md#switch-v5-proposal).

Answering the questions above, in my implementation the failure by `then` schema (or if `then` is false) is final, `switch` fails at this point regardless the value in `continue`. The success by `then` can still lead to the failure of `switch` if `continue` is true and the next `then` fails.

**Comment by sam-at-github** [comment]
:+1: Yep I like it. That interpretation makes the most sense.

**Comment by sam-at-github** [comment]
I was just over `dependencies`. A natural alternative to switch, would be, to allow `dependencies` to be an array of [schema, schema] pairs. The second is required if the first validates. Currently `dependencies` is a kind of shorthand for this anyway.

Although it does not have all of the capabilities of switch. Specifically the ability to continue, and break. But just want to note and compare this alternative anyway.

**Comment by robbie-mac** [comment]
I think this misses the point of a schema entirely. Why the need to add logic to a meta-data format? A schema is not a definition of the data, it is a description of what the data CAN contain. If the logic is taken out, the solution is already in draft 04, 'oneOf', and as @sam-at-github mentioned `dependencies`

**Comment by TaylanUB** [comment]
@robbie-mac Is there any actual disadvantage in adding such functionality to JSON Schema? Does it, for instance, change the algorithmic complexity in some fundamental way that rules out certain efficient implementations, or some such thing? I doubt it, since I think the functionality of `switch` can already be imitated with some complex use of `allOf`/`anyOf`/`not`, and some repetition. Note that `allOf` and `anyOf` are essentially `and` and `or`, from which propositional `if` can be constructed.

I'm interested in hearing your opinion. I'm sympathetic towards the idea of clear separation of concerns / layers of validation. (Akin to how code can fail during token parsing, fail at compilation or interpretation because the syntax tree is invalid, or fail at runtime due to an unhandled situation...)

**Comment by mbroadst** [comment]
@robbie-mac yeah I'd also like clarification on your position. There seems to be a sort of purist approach to the schema put forth by some of the community, but I struggle to see the downside of allowing these types of constructs that improve the "flow" of the schema definition.

I agree that this behavior can absolutely be implemented using v4, but you generally need to contort the logic to implement what is otherwise very easily mentally mapped as a `switch`. To borrow from an issue I opened [here](https://github.com/json-schema-org/json-schema-spec/issues/34), let's say we have the following (notedly contrived) example schema:

in english: a network interface where interface and dhcp are required, but if dhcp is set to true then we also require ip, mask, and gw

the first way I implemented this with `anyOf`:
```
{
  type: 'object',
  anyOf: [
    {
      properties: {
        interface: { type: 'string' },
        dhcp: { constant: false },
        ip: { type: 'string', format: 'ipv4' },
        mask: { type: 'string', format: 'ipv4' },
        gw: { type: 'string', format: 'ipv4' }
      },
      required: [ 'hostid', 'interface', 'dhcp', 'ip', 'mask', 'gw']
    }, {
      properties: {
        interface: { type: 'string' },
        dhcp: { constant: true },
        ip: { anyOf: [ {type: 'string', format: 'ipv4'}, { type: 'null' } ] },
        mask: { anyOf: [ {type: 'string', format: 'ipv4'}, { type: 'null' } ] },
        gw: { anyOf: [ {type: 'string', format: 'ipv4'}, { type: 'null' } ] }
      },
      required: [ 'hostid', 'interface', 'dhcp' ]
    }
  ]
}
```

a cleaned up approach suggested by Austin Wright:
```
{
  type: 'object',
  properties: {
        "interface": { type: 'string' },
        "dhcp": { type: 'boolean' },
        "ip": { type: 'string', format: 'ipv4' },
        "mask": { type: 'string', format: 'ipv4' },
        "gw": { type: 'string', format: 'ipv4' }
  },
  required: [ 'hostid', 'interface', 'dhcp' ],
  oneOf: [
    { properties: { "dhcp": { enum: [false] } }, required: ['ip', 'mask', 'gw'] },
    { properties: { "dhcp": { enum: [true] } } }
  ]
}
```

and a "v5" approach using ajv:
```
{
  type: 'object',
  properties: {
    interface: { type: 'string' },
    dhcp: { type: 'boolean' },
    ip: { type: 'string', format: 'ipv4' },
    mask: { type: 'string', format: 'ipv4' },
    gw: { type: 'string', format: 'ipv4' }
  },
  required: [ 'hostid', 'interface', 'dhcp' ],
  switch: [{
    if: { properties: { dhcp: { constant: false } } },
    then: { required: [ 'ip', 'mask', 'gw' ]}
  }]
}
```

When I wrote out the first approach I almost decided to stop using json-schema all together, it just didn't seem expressive enough and was incredibly verbose for this relatively simple case. I agree the cleaned up solution provided by Austin is essentially the same as the final version with switch, but I think the switch approach "reads" better than either of the other two. Specifically: there is less cognitive overhead when I read through that schema, it's very clear exactly what the conditions are.

It's been suggested I just don't get json-schema, and perhaps that's true, but I would really appreciate some clarification on that point 😄

**Comment by TaylanUB** [comment]
Matt Broadstone <notifications@github.com> writes:

> ...
> but if dhcp is set to true then we also require ip, mask, and gw
> ...

I assume you meant set to false.  Just to clear up confusion.

**Comment by mbroadst** [comment]
@TaylanUB yes you're right, apologies for the confusion there

**Comment by handrews** [comment]
This discussion has been moved to the new repository, on a new issue filed covering both `switch` and an alternative: https://github.com/json-schema-org/json-schema-spec/issues/64

**Comment by handrews** [comment]
@epoberezkin could you close this now that we have json-schema-org/json-schema-spec#64 (which includes the switch proposal although it might not be obvious at first).

If there are parts of this you would like to keep separate, please file a new separate issue in the new repo.
