### ISSUE TITLE
draft-04/schema: Should `simpleTypes` have "array" member in enum?

### ISSUE THREAD

**Issue by kzc** [json-schema/json-schema#230]
Given that the definition of `type` is an **`anyOf`** of `simpleTypes` ***or*** an array of `simpleTypes`:

        "type": {
            "anyOf": [
                { "$ref": "#/definitions/simpleTypes" },
                {
                    "type": "array",
                    "items": { "$ref": "#/definitions/simpleTypes" },
                    "minItems": 1,
                    "uniqueItems": true
                }
            ]
        },

https://github.com/json-schema/json-schema/blob/ebd207685a01020df416decbac61d9d1e1660e47/draft-04/schema#L129-L139

isn't it ambiguous/incorrect to have `"array"` as an `enum` member of `"simpleTypes"`?

        "simpleTypes": {
            "enum": [ "array", "boolean", "integer", "null", "number", "object", "string" ]
        },

https://github.com/json-schema/json-schema/blob/ebd207685a01020df416decbac61d9d1e1660e47/draft-04/schema#L18-L20

The first subschema of the `"type"` `anyOf` could technically be the only schema that need be matched for an array:

                { "$ref": "#/definitions/simpleTypes" },

and as such it would be incomplete - lacking the other properties of an array seen in the second `anyOf` subschema:

                {
                    "type": "array",
                    "items": { "$ref": "#/definitions/simpleTypes" },
                    "minItems": 1,
                    "uniqueItems": true
                }

**Comment by Ixrec** [comment]
I don't see any ambiguity here. A schema that says `"type": "array"` or `"type": [ "array" ]` indicates the value must be an array, but a schema that says `"enum": [ "array" ]` indicates the value must be the string literal `"array"`.

If schema X uses `"type": "array"` and schema Y uses `"type": [ "array" ]`, then when validating schema X against this metaschema you'll use the "first branch" of the `anyOf`, and when validating schema Y against this metaschema you'll use the "second branch" of the `anyOf`, so neither is unnecessary for arrays.

If you still think there is something "ambiguous or incorrect" about this, please provide a specific example of a schema that either should validate under the metaschema but doesn't, shouldn't validate under the metaschema but does, or can be interpreted in multiple ways by this metaschema. Right now I'm simply not seeing how any of those things could happen, and I can't tell if I'm confused because you're misunderstanding the spec or if I'm confused because I'm misunderstanding you.

**Comment by fge** [comment]
@kzc there is no ambiguity at all here.

`enum` takes a JSON Array as an argument and members of these arrays are JSON values which, for a given JSON Pointer, the instance to be validated must match _exactly_.

Which means that with such an enum as:

```
    "enum": [ "array", "boolean", "integer", "null", "number", "object", "string" ]
```

then the instance must be either of JSON String `array` or `boolean` or... etc etc.

It is VERY important to recall that values in an `enum` can be any JSON value, so this is legal as well:

```
    "enum": [ [ 1, 2 ], { "foo": "bar" }, false, null, 2.0020103 ]
```

**Comment by kzc** [comment]
Thanks the explanations. It was my misunderstanding the schema spec.

Is a v4 schema with `"type": [ "array" ]` functionally equivalent to a schema that says `"type": "array"`? 

Is the square bracketed form for `type` a throwback to the v3 syntax for multiple types instead of using `anyOf`?

**Comment by Ixrec** [comment]
I'm fairly sure `"type": [ "array" ]` and `"type": "array"` will do exactly the same thing. [Section 5.5.2 of the spec](http://json-schema.org/latest/json-schema-validation.html#anchor79) doesn't explicitly specify any difference in behavior between the array and the string form, and I can't come up with any sane way of interpreting that section which would imply a difference in behavior either.

Although I can't help but notice this section of the spec does not say the array form has to have at least one element, so the `"minItems": 1` part of the metaschema seems like it's _technically_ incorrect.

I have no idea if this syntax is a "throwback to v3", though I can say there are some schemas where I work which would be a lot less readable if we had to use `anyOf` for every single value where multiple types were allowed.

**Comment by kzc** [comment]
Thanks again for the clarification.
