### ISSUE TITLE
Properties that are both required and have default value

### ISSUE THREAD

**Issue by micovery** [json-schema/json-schema#238]
What does it mean for a property to have both default value, and at the same time be listed as a required property? Is the property required or is it optional?

The draft-v4 spec does not say it's illegal ... but the concept itself is contradictory.

Doesn't the presence of a `default` value for a property imply that the property it is optional?

In the XML schema spec, for example, they address this specific issue for XML element attributes.

https://www.w3.org/TR/xmlschema11-1/#sec-src-attdecl

![image](https://cloud.githubusercontent.com/assets/1885394/14758444/752aa6b8-08b6-11e6-880e-110b15afcfe0.png)

**Comment by sam-at-github** [comment]
`default` does not have any meaning with respect to the validation. Conceptually the default value *may* be swapped in where a value is not supplied. But its implementation specific. Then validation occurs. That is presumably why "It is RECOMMENDED that a default value be valid against the associated schema. " -  http://json-schema.org/latest/json-schema-validation.html#anchor101

**Comment by micovery** [comment]
@sam-at-github, thanks for the clarification ... 

So if the presence of the `default` value implies nothing for validation purposes ...

Then, what is the use-case of specifying a `default` value for a field that is also marked as required?

Am I alone in thinking that its contradictory?

**Comment by sam-at-github** [comment]
Supposing you validator does in fact interpret and use `default` this way (and its not just used as an informative hint to the front end UI), there isn't one. But as I said, so what.

These two concepts are provided to you as is. Simple. There is a combination of the two in there that does not make much sense. It's obvious. The alternative is the over specify like XSD.

**Comment by YurySk** [comment]
default maybe useful for the process that forms the data when the property has not been specified. For instance a blank form may be generically prefilled with default values. That has no bearing on whether the property is required or not.
You might argue that this is an application specific thing that can be expressed in a non-schema property since it has no bearing on validation, but given that default is in the spec applications might as well use it.

**Comment by handrews** [comment]
@micovery This repo is obsolete and no one still with the project is able to close issues here.  Could you please close this?

If you would like to continue the discussion, you are welcome to re-file it at [json-schema-org/json-schema-spec](https://github.com/json-schema-org/json-schema-spec/issues)?

As a side note, there are many legal but odd-to-nonsensical combinations possible in JSON Schema   This is generally by design, as strange fragment schemas are often useful for combinations with other schemas, particularly when "not" is involved.

**Comment by micovery** [comment]
Closing as per request.
