### ISSUE TITLE
Additionalproperties considers properties and patternProperties but not "required"

### ISSUE THREAD

**Issue by redben** [json-schema/json-schema#240]
Say you have an API for creating and updating profiles, both operations require different subsets of properties : 
- on create json must only contain `email` and `name` (`id` is generated), 
- on update json must only contain `id` and `email` (`name` is read only)

If additionalProperties considered `require`, it would make the schema this simple : 

``` json
{
  "properties": {
    "id": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    },
    "email": {
      "type": "string"
    },
  },
  "definitions": {
    "post": {
      "allOf": [{
        "$ref": "#/"
      }, {
        "required": ["name", "email"],
        "additionalProperties": false
      }]
    },
    "put": {
      "allOf": [{
        "$ref": "#/"
      }, {
        "required": ["id", "email"],
        "additionalProperties": false
      }]
    }
  }
}
```

Any thoughts ?

**Comment by YurySk** [comment]
I don't think V4 allows ref to be empty fragment. Not sure what '#/' means in terms of URI, but suspect it's the same as # I.e. a uri with an empty fragment

**Comment by JanTvrdik** [comment]
> Not sure what '#/' means in terms of URI

See https://tools.ietf.org/html/rfc6901#section-6, `#` is reference to the whole document, `#/` is reference to key `""` (empty string). Unfortunately not all libraries implement this correctly.

**Comment by YurySk** [comment]
Thanks, I need to make sure I interpret it correctly.

**Comment by jdesrosiers** [comment]
That's an interesting thought.  In a sense, `required` implies the definition of those properties.  You could say that if a required property is not defined, it is equivalent to a defined property with an empty schema.  That isn't the way `required` is currently defined, but it wouldn't be an illogical change in a future draft.

Getting slightly off topic ...
You wouldn't have this problem if you moved the `additionalProperties` keyword to the root of the schema.  I assume you did that for valid reasons such as wanting to keep the base schema extendable.  Just thought I would mention it in case you missed that.

A little more off topic ...
I don't understand why people insist on using `additionalProperties`.  Is there really a good reason why the program can't just ignore properties it doesn't understand?  Is that reason worth the pain `additionalProperties` almost always causes?

Yet more off topic ...
I just want to make sure you are aware of JSON Hyper-Schema for defining your `post` and `put` operations rather than just putting them in the definitions.  http://json-schema.org/latest/json-schema-hypermedia.html

**Comment by Ixrec** [comment]
@jdesrosiers To continue being off-topic, a few months ago we discovered we had a very large number of outdated models in our database (as in, so outdated our app would crash if it tried to load them) all because `additionalProperties: false` caused validation failures on one of those old schemas with long-deprecated properties. As scary as the discovery was, not finding it would've been far worse.

The way we use JSON Schemas, insisting that an object not have any additional properties is like insisting that you pass the correct types to our Javascript functions. We _could_ simply return `undefined` if any of the argument types are wrong, but it's better to fail fast. We've also had cases where a function was being passed object literals with "unnecessary" properties, and then something deeper down the call stack was depending on those properties, creating a very non-obvious coupling which using proper schemas and tests quickly exposed so we could refactor it.

So yes, `additionalProperties` definitely has value. And somehow we haven't encountered problems with it.

**Comment by jdesrosiers** [comment]
@Ixrec You might have a case where you can answer "yes" to the questions I posed.  But I don't think that is the general case.  I have seen a few cases where `additionalProperties` was necessary to express a structure, but that is only in rare and complex cases.  However, the people seem to default to using it when it is unnecessary.  To make an analogy to OO, it's like closing a class to extension.  Sometimes it's a good idea, but not in the general case.

> The way we use JSON Schemas, insisting that an object not have any additional properties is like insisting that you pass the correct types to our Javascript functions. 

I'm afraid I don't understand how this example shows the benefit of the `additionalProperties` constraint.  

> We could simply return undefined if any of the argument types are wrong, but it's better to fail fast.

If the argument types were wrong or missing, wouldn't it fail validation on `properties` or `required`?  What does this have to do with `additionalProperties`?  I agree that fail-fast is best, but I don't see how `additionalProperties` helps achieve that goal.

> We've also had cases where a function was being passed object literals with "unnecessary" properties, and then something deeper down the call stack was depending on those properties

It sounds like you are saying that "unnecessary" properties are triggering unwanted behavior.  My suggestion was that unwanted properties be ignored.  If they are triggering behavior, then they are not being ignored.

At this point, I remain unconvinced.

**Comment by redben** [comment]
*Moving additionalProperties to the root...*
moving additionalProperties to the root schema wouldn't help since a document witj `{"id","name","email"}` would still validate with post or put


*Doing without additionalProperties*
You are right more often than not you can do with out it, some frameworks default to what could be mapped to additionalProperties=false (Jackson (java) for example defaults to ignoreUnknownProperties=false). So yeah turning that feature on eases the pain...

On the other hand, additionalProperties makes the contract clear. Let's say we don't use it and some api client developer (misunderstanding the documentation) sends a document with property `avatar`. The api does not complain. Elsewhere in the process, the client reads the profile resource but can't see his avatar property (you know how debugging these situations can go...)

You could say well it's the developer's fault, he should have RTFM... Right. But isn't a schema supposed to be the number one source of documentation ?

*Yet more off topic ...*
JSON Hyper-Schema : indeed, I included definitions just for the sake of a simplicity

**Comment by redben** [comment]
Forgot to mention a workaround (as long as you don't have reasonably few properties) 
One can add patternProperties like this:

```json
  "post": {
      "allOf": [{
        "$ref": "#/"
      }, {
        "required": ["name", "email"],
        "patternProperties": {
          "^name|email$": {}
        },
        "additionalProperties": false
      }]
  }
```

**Comment by jdesrosiers** [comment]
*Moving `additionalProperties` to the root*
Oops, I missed the part where "name" is supposed to be read-only.  In that case, there is the `readOnly` property, but only if you are using Hyper-Schema.

*Doing without `additionalProperties`*
Ok, I agree that in the situation you describe, `additionalProperties` would have helped.  But, you have to admit its pretty convoluted.  The developer would have to ignore the schema twice: going in and coming out.  It comes down to that second question I posed: Is it worth the restrictions and complications introduced by `additionalProperties`?  For me, the answer is still no.

**Comment by handrews** [comment]
This discussion has been migrated to https://github.com/json-schema-org/json-schema-spec/issues/65

**Comment by handrews** [comment]
@redben if the discussion in json-schema-org/json-schema-spec#65 covers this topic, could you please close this issue so we have one clear place for tracking?
