### ISSUE TITLE
Too much indirection in `5.2 rel` chapter of Hyper Schema Spec

### ISSUE THREAD

**Issue by vanthome** [json-schema/json-schema#92]
In this chapter you describe that rel stems from the ATOM syndication format and that there is a registry...
However, in the mentioned RFC 4287, there is a dead link to the IANA Link Relations registry. In my opinion it is better to directly reference it:
http://www.iana.org/assignments/link-relations/link-relations.xml

**Comment by handrews** [comment]
@vanthome 
This bug has been fixed in the latest draft:
https://tools.ietf.org/html/draft-wright-json-schema-00
https://tools.ietf.org/html/draft-wright-json-schema-validation-00
https://tools.ietf.org/html/draft-wright-json-schema-hyperschema-00
spec work is now at https://github.com/json-schema-org/json-schema-spec
Could you please close this?

**Comment by vanthome** [comment]
sure
